package com.treeki.treekii;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class MainActivity extends AppCompatActivity {

    private DatabaseReference mDatabase;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mDatabase = FirebaseDatabase.getInstance().getReference();
        String month;
        String day;
        int total_days = 0;
        int cur_q = 0;
        String[] questions = {"What is your favorite food?",
                "What is your favorite song?",
                "What is one thing that happened today that you’re thankful for?",
                "What type of dream did you have today?",
                "How would you describe your fashion style?",
                "Where are you right now?",
                "What is the app you use most of this phone?",
                "Who is your favorite music artist?",
                "What is the last book you read for enjoyment?",
                "What is the last game you played?",
                "What is the one achievement you are most proud of doing?",
                "When was the last time you asked someone for help? What was the request?",
                "When was the last time you helped someone? How did you help?",
                "What did you eat for breakfast today?",
                "When was the last time you pampered yourself? What did you do?",
                "On a scale from 1-10, how satisfied are you with your life right now? Why?",
                "What is something you learned recently?",
                "When was the last time you cried? Why?",
                "If you had to choose a color to describe your mood right now, what would it be?",
                "What is your favorite hobby?",
                "What is your current favorite piece of clothing?",
                "Who is your role model?",
                "What was the last vacation you went on?",
                "What is one thing that calms you down?",
                "Who is the last person you told “I love you”?",
                "If a random person went up to you on the street and asked you to lend $5, would you do it? Why or why not?",
                "What is the best gift you received from someone? The worst gift?",
                "What is the most thoughtful gift you’ve ever given someone?",
                "What is the last show you’ve watched? Did you like it? Why or why not?",
                "What is the last movie you’ve watched? Did you like it? Why or why not?",
                "What is one thing you hope never changes in your life?",
                "What is one thing you want to change in your life?",
                "What is one thing you can’t give up in your life?",
                "Who is the last person you forgave? What did they do?",
                "Who was the last person to forgive you? What did you do?",
                "If you can turn into any one animal for a week, what animal would you choose? Why?",
                "If you can have any one super power for a week, what would you choose? Why?",
                "What is your favorite thing about yourself? Your least favorite?",
                "What is one thing you’d like improve yourself on?",
                "What is one thing you regret not doing?",
                "What is one thing you are guilty of doing?",
                "What are three words you would describe yourself with? Why?",
                "Out of the people you are closest to in your life, who do you think you are the most similar to? Why?",
                "Out of the people you are closest to in your life, who do you think you are the most different from? Why?",
                "Would you be willing to sacrifice yourself for another person? Why or why not? If yes, what would the circumstances be?",
                "Who was the last person to inspire you? What was the inspiration?",
                "Name 3 people you can’t live without right now.",
                "What story inspires you? What was it about?",
                "Hot or cold? Why?",
                "Do you take good care of the environment? Why or why not?",
                "If you could switch lives with one person in the entire world, who would you choose? Why?",
                "What is your dream?",
                "What is your favorite beverage?",
                "If you could redo one moment in your life, what would it be? Why?",
                "Who is someone you miss currently? Do you keep in touch with them?",
                "What languages can you speak? What languages would you like to learn?",
                "What are the top three places you would like to live in?",
                "Do you care more about a person’s appearance or personality? Why?",
                "What is your favorite topic to study about? Why?",
                "What is your dream job realistically? Why?",
                "Do you support the current leader of your country? Why or why not?",
                "What would you call your passion?",
                "Who do you respect the most in your life? Why?",
                "If you had to use one animal to describe yourself, what animal would it be?",
                "What is your biggest pet peeve?",
                "What is one thing that relaxes you? Why?",
                "If you were stranded on an island, what would be the first thing you’d do?",
                "What are you craving for right now?",
                "What is your battery percentage?",
                "What are you doing now?",
                "When did you wake up today?",
                "How much do you weigh?",
                "What is the most important thing for you ?",
                "What is your goal for the day?",
                "What annoys you the most?",
                "If you can start over from one day this year, what day would it be?",
                "What is the most exciting thing that happened to you recently?",
                "What is the most upsetting thing that happened to you recently?",
                "If you have to lose a “friend”, which friend would it be?",
                "Would you prefer to be your gender or the opposite gender and why?",
                "What is your favourite tv show?",
                "What is your favourite movie?",
                "What is your dream job if not concerned about reality?",
                "Would you lose the one you love the most for a billion dollars?",
                "What phone are you using and how do you like it?",
                "What hobby would you get into if you don't need to worry about time and money?",
                "How often do you play sports?",
                "Would you quit your job?",
                "What would you do with the extra time if you did not need to sleep?",
                "What would you want to do again?",
                "What is your short term goal and long term goal?",
                "Would you get a tattoo? If yes, what would you get? If no, why not?",
                "Where is your favorite place to relax?",
                "What is your favorite memory with your parents?",
                "If you had infinite money how would you spend your time?",
                "What is your earliest memory?",
                "How many alarms do you set in the morning? How many does it take for you to actually get up?",
                "What happens when you die?",
                "What does your dream family look like?",
                "How many pets do you have? How many pets would you like to have?",
                " What is your favorite all time video game?",
                "What could you do forever without ever getting tired of?",
                "What is one bad habit you wish you could break?",
                "What is the best hike you’ve ever been on?",
                "If you could have any animal for a pet what would you want?",
                "If you could only eat one thing for the rest of your life what would you want to eat?",
                "If you were on death row what would your last meal be?",
                "What is the most useless fact you know?",
                "How long do you think you will live for?",
                "What are the top 3 things on your bucket list?",
                "Would you like to have a twin?",
                "Who was your favorite teacher in elementary/middle/high school?",
                "Do you want kids? If yes, how many? If no, why not?",
                "How many close friends do you have?",
                "What is your favorite kind of music?",
                "If you could instantly learn a skill what skill would you like to learn?",
                "How much sleep do you need to function?",
                "If you could talk to elephants what would you ask them?",
                "What is your biggest fear?",
                "What is the biggest thing stopping you from reaching your goals?",
                "What is your favorite restaurant?",
                "What do you miss most about being in elementary school?",
                "If you could live anywhere in the world to live where would you live?",
                "What makes you feel better no matter how bad you feel?",
                "How do you fall asleep?",
                "Do you think Pluto is a planet?",
                "Would you live on Mars?",
                "Are you a cat person or a dog person?",
                "What is your favorite kind of candy?",
                "How many licks does it take to get to the center of a tootsie pop?",
                "If you could do anything with no consequences what would you do?",
                "Do you believe in ghosts?",
                "Would you rather you were a 10/10 and your partner was ugly or you were ugly and your partner was a 10/10?",
                "What are you most looking forward to right now?",
                "What do you wish you had right now?",
                "What is your favorite pokemon?",
                "What is your favorite sport?",
                "What is your favorite sports team?",
                "Yellow, black, or chocolate lab?",
                "What is your favorite dessert?",
                "How many new states/ countries did you visit this year?",
                "What is your best business idea?",
                "What are you most insecure about?",
                "What are you goals for the next year?",
                "What is your favorite season?",
                "What is your best memory of the past year?",
                "What is your biggest regret from the past year?",
                "Would you rather go into the past or the future?",
                "What can you not leave your house without?",
                "When was the last time you laughed so hard you cried?",
                "What makes you happy?",
                "What temperature do you like the room to be when you sleep?",
                "What is the best advice you could give to your future self?",
                "What is the best advice you could give to your past self?",
                "Would you take the path less traveled?",
                "Star Wars, Star Trek, or neither?",
                "Do you procrastinate too much?",
                "What is your dream car?",
                "What’s your favorite kind of ice cream?",
                "Is there a place that you know very many facts about, even though you've never been there?",
                "What is something that never fails to cheer you up?",
                "In your opinion, what kind of pet is the most cuddly and affectionate?",
                "What is the biggest fashion violation?",
                "What is something you accomplished as a child that you are still proud of to this day?",
                "Where is your ideal vacation destination?",
                "Name a fruit that is generally overpriced at the supermarket?",
                "Is there anybody you would like to trade bodies with for a day?",
                "Which popular hairstyle is going to go out of style this year?",
                "Why is the universe expanding? 🤔",
                "Have you ever told a lie that came back to bite you?",
                "What is the best book you have ever read?",
                "Your worst nightmare?",
                "When you find an extra cute top, do you check the price tag before buying it?",
                "Have you you ever thirsted for forbidden knowledge?",
                "Who is the least scummy politician?",
                "Can people change?",
                "What was the last restaurant you went to?",
                "You are lucky; how so or not so?",
                "Was today typical? What did you do today?",
                "Are you a leader or a follower?",
                "What was the best meal you’ve had this week?",
                "Do you owe anybody money? Does anybody owe you money?",
                "What’s the oldest thing you’re wearing today?",
                "Are you holding a grudge? About?",
                "What are you looking forward to?",
                "Do you seek adventure or security?",
                "Do you need a break? From what?",
                "What makes you “you”?",
                "Today you need more ____?",
                "How do you describe home?",
                "What was the last TV show you watched?",
                "What do you want to forget?",
                "Who do you want to be?",
                "Who do you live with?",
                "On a scale of 1-10, how happy are you?",
                "Are you in love?",
                "How late did you sleep?",
                "What is your biggest obstacle right now?",
                "What’s your favorite question to ask people?",
                "VALENTINE’S Did you kiss someone today?",
                "What’s the most expensive thing you’re wearing right now?",
                "Salty or sweet?",
                "What’s your favorite word?",
                "Who’s your nemesis?",
                "What’s something you want but can’t have?",
                "Where do you live?",
                "What new activity have you tried recently?",
                "Describe your work ethic.",
                "When was the last time you felt like you were on top of the world?",
                "What invention can you not live without?",
                "What is your favorite thing to do on a Sunday morning?",
                "If you could acquire a talent (without any effort), what would it be?",
                "What do you think is your biggest shortcoming?",
                "What’s a problem you solved today?",
                "Who would you bring back from the dead to have dinner with?",
                "How many times did you curse today?",
                "How would your parents describe you? (Call them and ask!)",
                "Messy or neat?",
                "What do you want to postpone? ",
                "How do you want to be remembered?",
                "What are you exploring? ",
                "What’s the craziest thing you’ve done recently?",
                "What’s your salary?",
                "When was the last time you had a deep/inspiring conversation",
                "What gives you comfort right now?",
                "If you didn’t have any responsibilities for the day, what would you do?",
                "How much money do you have? ",
                "How healthy are you?",
                "Who do you miss the most right now?",
                "Who’s your best friend?",
                "What makes a good friend?",
                "What’s your favorite activity to do on a Friday night?",
                "What made you worry today?",
                "The best hour of today was _____. Why?",
                "What’s the last meal someone cooked for you? When?",
                "Who do you want to know better? Why?",
                "When was the last time you cried?",
                "What’s your biggest indulgence?",
                "If your mood were a weather forecast, what’s the weather like?",
                "What are the top songs on your “most played” list?",
                "What is your motto?",
                "What do you have to lose?",
                "When was the last time you spoke to your parents?",
                "____ is perfect.",
                "Do you have a secret? More than one?",
                "What are the ingredients for a perfect day?",
                "Does anything hurt today?",
                "Who was the last person to make you angry? Why?",
                "What was the last thing you baked/cooked?",
                "What was the last road trip you took?",
                "What do you lie about?",
                "What was your last great meal?",
                "Do you make enough money?",
                "What was your last text?",
                "What are you running from at this moment?",
                "Did you complete your to-do list today?",
                "What question(s) do you love to answer?",
                "What can’t you forget?",
                "What’s your plan for the future?",
                "What’s your recipe for creativity?",
                "What’s the best part about your life right now?",
                "What’s your simplest pleasure?",
                "Are you a teacher or a student?",
                "Is your room clean?",
                "Where do you see yourself in five years?",
                "Who are you jealous of?",
                "What comes to mind when you think of fear?",
                "What’s a minor, but chronic problem?",
                "Who are the most important people in your life?",
                "What’s your favorite snack?",
                "What was the hardest decision you made today? What made it hard?",
                "What shocking news have you recently learned?",
                "What’s your favorite quote? ",
                "Planned or spontaneous? Why?",
                "Do you handle rejection well? Why/Why not?",
                "Bad news: sugarcoated or straight up? Why?",
                "Good or bad news first? Why?",
                "How do you get out of a rut?",
                "What are you a geek about?",
                "What are you craving?",
                "You want a new ____.",
                "What makes you feel wonderful?",
                "What do you have no patience for?",
                "What expression do you overuse?",
                "What’s the most valuable item you own?",
                "What was your last purchase? ",
                "Who do you rely on?",
                "Camping or hotel?",
                "What’s something you couldn’t do today?",
                "Who is your hero?",
                "What do you always avoid?",
                "What’s missing in your life?",
                "What do you need to vent about?",
                "What are you obsessed with?",
                "What do you have to get done?",
                "What was the last risk you took?",
                "What would you like your epitaph to read?",
                "Do you want to know how it ends? Why/ Why not?",
                "Who do you miss?",
                "What do you find irresistible?",
                "What do you like to talk about?",
                "If you could be the best at anything, what would it be?",
                "Have you met someone new recently? If so, who was it? If not, do you want to?",
                "What was the last gift you gave? Received?",
                "Outside or inside? Why?",
                "What is your most cherished memory of this year?",
                "When you are old, what do you think children will ask you to tell stories about?",
                "Where do you get your news?",
                "What movie can you watch over and over without ever getting tired of?",
                "If you couldn’t be convicted of any one type of crime, what criminal charge would you like to be immune to?",
                "In the past people were buried with the items they would need in the afterlife, what would you want buried with you so you could use it in the afterlife?",
                "What food have you never eaten but would really like to try?",
                "What would a world populated by clones of you be like?",
                "What is your #1 most important rule when going on a date?",
                "What outdoor activity haven’t you tried, but would like to?",
                "If you were moving to another country, but could only pack one carry-on sized bag, what would you pack?",
                "What about the opposite sex confuses you the most?",
                "What kinds of things do you like to cook or are good at cooking?",
                "If you could hack into any one computer, which computer would you choose?",
                "What’s about to get much better?",
                "What did you Google last?",
                "If you had a HUD that showed three stats about any person you looked at, what three stats would you want it to show?",
                "What does your ideal world look like?",
                "When was your last all-nighter? Why'd you stay up all night?",
                "If you owned a restaurant, what kind of food would it serve?",
                "What topic could you spend hours talking about?",
                "What do you do to make the world a better place?",
                "What do you need help with most often?",
                "What values are most important to you?",
                "What do you think you do better than 90% of people?",
                "What’s your favorite drink?",
                "What songs have you completely memorized?",
                "Are you usually early or late? Why?",
                "Do you eat breakfast regularly? Lunch? Dinner?",
                "Do you prefer to be alone or be around friends?",
                "What do you drink most everyday?",
                "What’s something you like to do the old-fashioned way?",
                "What takes up too much of your time?",
                "How often do you people watch?",
                "What’s worth spending more on to get the best?",
                "What amazing thing did you do that no one was around to see?",
                "How different was your life one year ago?",
                "What’s the best way to start the day?",
                "What would you rate 10/10?",
                "What do you hope never changes?",
                "What’s the best way a person can spend their time?",
                "What are you looking forward to in the coming months?",
                "What website do you visit most often?",
                "Where would you spend all your time if you could?",
                "How do you hope you’ll change as a person in the future?",
                "What keeps you up at night?",
                "What are you most insecure about?",
                "How do you get in the way of your own success?",
                "What’s one thing you did that you really wish you could go back and undo?",
                "What's your spirit animal?",
                "What’s the best and worst thing about getting older?",
                "Among your friends or family, what are you well-known for?",
                "What are the top three things you want to accomplish before you die? How close are you to accomplishing them?",
                "What’s one responsibility you really wish you didn’t have?",
                "What are some of your personal “rules” that you never break?",
                "What have you created that you are most proud of?",
                "What’s the title of the current chapter of your life?",
                "What would a mirror opposite of yourself be like?",
                "What stat for your life would you most like to see?",
                "When do you feel truly “alive”?",
                "What makes a good life?"
        };

        for (int i = 1; i <= 12; i++){
            switch(i) {
                case 1: total_days = 31;
                    break;
                case 2: total_days = 29;
                    break;
                case 3: total_days = 31;
                    break;
                case 4: total_days = 30;
                    break;
                case 5: total_days = 31;
                    break;
                case 6: total_days = 30;
                    break;
                case 7: total_days = 31;
                    break;
                case 8: total_days = 31;
                    break;
                case 9: total_days = 30;
                    break;
                case 10: total_days = 31;
                    break;
                case 11: total_days = 30;
                    break;
                case 12: total_days = 31;
                    break;
            }
            for (int j = 1; j <= total_days; j++){
                month = Integer.toString(i);
                day = Integer.toString(j);

                mDatabase.child("Questions").child(month).child(day).setValue(questions[cur_q]);
                cur_q++;
            }
        }
    }
}
